version: '3.4'

services:
  db:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123123root
      - MYSQL_DATABASE=transactions
      - MYSQL_USER=transaction
      - MYSQL_PASSWORD=123123
    command: --max_allowed_packet=512M --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
