version: '3.4'

services:
  db:
    container_name: db_transactions
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123123root
      - MYSQL_DATABASE=transactions
      - MYSQL_USER=transaction
      - MYSQL_PASSWORD=123123
    command: --max_allowed_packet=512M --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  nginx:
    image: nginx:latest
    container_name: nginx_transactions
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm

  phpfpm:
    container_name: phpfpm_transactions
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/html/app
    depends_on:
      - db
